### ISSUE TITLE
Cannot launch MuWire 0.0.2

### ISSUE THREAD

**Issue by sschindel** [zlatinb/muwire#1]
Hi,

launching MuWire 0.0.2 under Debian Buster (OpenJDK 11) seems not to work or I am missing some package:

`[main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:131)
`

**Comment by zlatinb** [comment]
Did you install OpenJDK from Debian?  Looks like there is something missing in the dependencies.  Can you try installing a JDK manually from https://jdk.java.net/12/

**Comment by sschindel** [comment]
Nope, exact the same issue :-/.

**Comment by zlatinb** [comment]
I was able to reproduce it with java 11 and found a fix.  Please give the latest master branch a try.

**Comment by sschindel** [comment]
Awesome, thanks, and yes it's working now :).
