### ISSUE TITLE
CPU usage jumps to 100% every 5s

### ISSUE THREAD

**Issue by zetok** [zlatinb/muwire#10]
MuWire seems to periodically (every 5s) use 100% CPU even though it's not doing anything aside from maintaining connectivity with other peers. It's probably not an intended behaviour?

MuWire version: `0.4.7`

```sh
$ dstat -cy
--total-cpu-usage-- ---system--
usr sys idl wai stl| int   csw 
  6   1  93   0   0|4821  4113 
  5   1  95   0   0|1343  2816 
  5   1  94   0   0|1270  3108 
  4   1  88   3   3|1224  3011 
  3   1  97   0   0| 974  2004 
  3   1  93   2   0|1074  2929 
 14   3  83   0   0|6862  8649 
 28   3  68   0   0|  10k   12k
 27   3  69   0   1|  10k   13k
 23   4  73   0   0|  10k   13k
 32   3  65   0   0|9210    12k
 29   4  66   0   1|  10k   12k
 20   2  78   0   0|  11k   12k
 23   3  74   0   0|6946    13k
 24   3  73   0   0|8492    11k
  9   4  82   1   3|3141  4638 
  1   1  96   2   0| 728  2197 
  3   1  96   0   0| 932  2332 
  2   1  96   1   0| 702  1590 
  3   0  97   0   0| 908  2509 
  2   2  96   0   0| 889  1974 
 16   2  81   0   0|6616  8037 
 30   2  68   0   0|6934    13k
 26   4  70   0   0|8289    12k
 26   3  71   0   0|7388    11k
 30   3  67   0   1|9916    12k
 24   3  72   0   1|  10k   12k
 20   2  78   0   1|  11k   12k
 27   3  69   0   1|  10k   12k
 27   3  70   0   0|  10k   12k
 13   4  82   0   1|3534  5286 
  2   1  97   0   0|1369  3588 
  2   1  96   0   0|1291  3698 
  3   1  90   4   2|1266  2665 
  3   1  96   0   0|1226  2782 
  4   1  94   0   0|1456  3729 
```

**Comment by zlatinb** [comment]
Every 5 seconds is strange.  The index of shared files gets rebuilt every 15 seconds, and if you are sharing many (as in thousands) files I would expect that to cause a short spike.
Is it possible for you to profile the process using visualvm?  That is a simple profiling tool that comes with OpenJDK.
Another thing that may give some hints is to enable logging.  In the `logging` directory in the source tree there are four pre-configured properties files that enable different levels of logging.  I suggest you start with `logging/3_logging.properties` by passing the following switch to the java command:
`-Djava.util.logging.config.file=/path/to/3_logging.properties`
The log file will appear in $PWD and be called MuWire.log.

**Comment by zetok** [comment]
>Every 5 seconds is strange. The index of shared files gets rebuilt every 15 seconds, and if you are sharing many (as in thousands) files I would expect that to cause a short spike.

Well, I do have a nice directory with 120k files that I'm planning to test MuWire with, but I've started off lightly with only a couple of hundreds of files.

>Is it possible for you to profile the process using visualvm?

I guess? I'm not sure what info to provide from it. Some screenshots:

![20190708 10:05:46 muwire visualvm monitor](https://user-images.githubusercontent.com/3148759/60800728-95e79480-a16d-11e9-9ff2-07acb65af9f4.png)
![20190708 10:09:18 muwire visualvm threads](https://user-images.githubusercontent.com/3148759/60801059-2faf4180-a16e-11e9-9534-fcdac56d3c35.png)

Threads `file persister` and its buddies `RMI TCP Connection` seem to use most of the CPU time.
![20190708 10:22:23 muwire visualvm sampler thread](https://user-images.githubusercontent.com/3148759/60801073-3b9b0380-a16e-11e9-9138-8baa6f602d2e.png)

I don't know much about java, but this doesn't look too great:
![20190708 10:27:39 muwire visualvm CPU sampler1](https://user-images.githubusercontent.com/3148759/60801153-64bb9400-a16e-11e9-8ddc-1a7e64f73be1.png)
![20190708 10:28:02 muwire visualvm CPU sampler2 png](https://user-images.githubusercontent.com/3148759/60801158-67b68480-a16e-11e9-9b9b-244dc193ae53.png)

If needed, I'll look into enabling logging later.

**Comment by zlatinb** [comment]
I think the answer is in the first screenshot - there is garbage collection every few seconds.  Are you passing any -Xmx switches to the JVM?  If not, try something like -Xmx512M or if you have more memory, even higher value.
The "file-persister" will start using cpu once you share the many files you have.  Be advised that with such high number of files the GUI has been reported to slow down and even freeze if you sort by any of the columns in the "Shared files" table.
If your files happen to be stored on a NAS or a server, you may want to look into the command-line interface in the "cli" sub-project.  More information available here https://muwire.com/muwire-cli.txt

**Comment by zetok** [comment]
MuWire version: `0.4.10`

>I think the answer is in the first screenshot - there is garbage collection every few seconds. Are you passing any -Xmx switches to the JVM? If not, try something like -Xmx512M or if you have more memory, even higher value.

I haven't passed any switches before. After starting it with `-Xmx1G` the CPU usage pattern remains the same. Also, the JVM process uses less than 500 MB of memory, so I doubt whether it's GC.

---

>Every 5 seconds is strange. The index of shared files gets rebuilt every 15 seconds, and if you are sharing many (as in thousands) files I would expect that to cause a short spike.

Actually, about that. I wrote "5s" since that was the idle period after which CPU would see an increased load period (and having assumed that whatever causes load would start after set amount of time since the time the previous run of the routine ended). Now that I took a look, the heavy load period takes about 10s, so the full cycle (idle time + heavy load time) does take about 15s.

**Comment by zlatinb** [comment]
If it is indeed the persisting of files that would be easy to verify with a small code change.  The following patch will make the persisting interval 1 minute https://gist.github.com/zlatinb/8486fbb9b27f8c8b3401e0bd662c3c14

**Comment by zetok** [comment]
Yep, with this patch applied MuWire stays almost idle for the most part. Increased CPU load starts every ~60s.

**Comment by zlatinb** [comment]
Few questions then:
* how many files are you sharing, roughly?
* are they mounted on a remote file system?
* is the $HOME/.MuWire mounted on a remote file system?
* can you try this patch https://gist.github.com/zlatinb/83997f20a5b4ddb5c4cddb177ddf8a56 and see if it improves cpu usage?

**Comment by zetok** [comment]
>how many files are you sharing, roughly?

~600

>are they mounted on a remote file system?

Not quite, but there is a performance bottleneck. I'm running MuWire in a LXC container inside a VM, and the filesystem is shared with VM as a read-only mount via [9P](https://en.wikipedia.org/wiki/9P_(protocol)), which is kinda slow (e.g. continuous file read is at 25-30 MB/s).

>is the $HOME/.MuWire mounted on a remote file system?

No.

>can you try this patch https://gist.github.com/zlatinb/83997f20a5b4ddb5c4cddb177ddf8a56 and see if it improves cpu usage?

Seems to help. 10-12s of heavy CPU usage decreased to 4-5s.

**Comment by zlatinb** [comment]
One last question - is the`/tmp` on the container/vm also mounted in some fashion that would cause writing to it to be slow?  When MW persists the file index it writes it to a temporary file, then copies that over `$HOME/.MuWire/files.json`
Other than that I've committed the second patch to master, but am reluctant to increase the interval at which persisting happens because there is a trade-off to be made with losing progress while files are hashed.

**Comment by zetok** [comment]
> One last question - is the`/tmp` on the container/vm also mounted in some fashion that would cause writing to it to be slow?

No.

>Other than that I've committed the second patch to master, but am reluctant to increase the interval at which persisting happens because there is a trade-off to be made with losing progress while files are hashed.

You might want to increase it to at least a minute (not much progress is lost in a minute), and maybe at some point make it an option for users (some bittorrent clients have an option for data/settings write interval (e.g. qBittorrent) and the minimum adjustable unit of time used for it is a minute. Also, writing to a file every 15s is not that great for SSD longevity.

BTW, would increasing interval to 600s or more cause any problems with connectivity? Because after doing that MW for some reason dropped all 20+ connections soon after launch when someone was downloading `MuWire-0.4.10.jar`. After that, MW didn't really recover from it, only managing to get 2-3 connections.

**Comment by zlatinb** [comment]
I'm fine with increasing it to a minute but if you have ~120K files you want to share and persisting 600 is taking 4 seconds, even a minute will not be enough.
Would you mind trying the following slightly riskier patch: https://gist.github.com/zlatinb/1b103defee306491d819816192ea9e60 on top of current master

> would increasing interval to 600s or more cause any problems with connectivity

It really shouldn't, the two are unrelated.

**Comment by zetok** [comment]
>Would you mind trying the following slightly riskier patch: https://gist.github.com/zlatinb/1b103defee306491d819816192ea9e60 on top of current master

There might be a bit lower CPU usage with it, but it's a bit hard to tell.

**Comment by zlatinb** [comment]
Well I've increased the persistence interval to one minute and committed the latest patch.  I'm curious to see if the CPU usage is linear with the number of shared files before I start looking into other optimizations.  A `kill -3` or `jstack <pid>` during the cpu spike or just more visualvm profiling would be helpful as it can suggest other clues.

**Comment by zlatinb** [comment]
Actually, please try this patch https://gist.github.com/zlatinb/a00dc7c9f00111eb4b47a99f43746dc9 - it eliminates one more filesystem call (to get the length()) of the file.

**Comment by zetok** [comment]
>Actually, please try this patch https://gist.github.com/zlatinb/a00dc7c9f00111eb4b47a99f43746dc9 - it eliminates one more filesystem call (to get the length()) of the file.

This significantly reduces CPU usage – from ~5s (on 2bb6826906679e88d82058f6a415d07cf11c7f0d) to a bit under 2s of heavy CPU load.

I've applied last patch on top of 2bb6826906679e88d82058f6a415d07cf11c7f0d to make testing faster.

Definite improvement compared to before:

```sh
$ dstat -cdy
--total-cpu-usage-- -dsk/total- ---system--
usr sys idl wai stl| read  writ| int   csw 
  6   1  93   0   0|  52k  733k|2723  3292 
  6   1  93   0   0|   0     0 |1599  3160 
  5   1  94   0   0|   0     0 |1816  3277 
 10   1  89   1   0|   0    88k|1673  3475 
 31   3  65   0   0|   0    32M|1934  3448 
  9   4  86   0   1|   0    37M|1804  3257 
  5   1  95   0   0|   0     0 |1679  2799 
  5   1  94   0   0|   0     0 |1615  3723 
  3   0  80  11   4|   0   120k|1422  3082 
  5   0  80  15   0|   0  4096B|1476  2791 
  4   1  95   0   0|   0     0 |1387  2725 
  4   1  95   0   0|   0     0 |1437  2819 
  4   1  95   0   0|   0     0 |1509  3598 
  5   1  94   1   0|   0   100k|1439  2809 
  4   1  94   0   0|   0     0 |1582  3060 
  5   1  94   0   0|   0     0 |1447  3154 
  6   1  93   0   0|   0     0 |1951  3830 
  5   1  93   1   0|   0   256k|1682  3410 
  8   1  91   0   0|   0     0 |1757  3082 
 28   3  68   0   1|   0    32M|2019  3464 
 10   4  87   0   0|   0    37M|1812  3954 
  5   1  94   0   0|   0     0 |1391  2953 
  6   1  74  15   4|   0   124k|1603  3469 
  5   1  71  22   0|   0  4096B|1618  3619 
  7   1  92   0   0|   0     0 |1468  2883 
  5   1  94   0   0|   0     0 |1646  3328 
  6   1  94   0   0|   0     0 |1611  3941 
  4   1  95   1   0|   0   112k|1564  2778 
  5   1  93   0   0|   0     0 |1769  3327 
  5   1  94   0   0|   0     0 |1573  3170 
  4   1  95   0   0|   0     0 |1278  2895 
  4   1  95   0   0|   0     0 |1522  3210 
  4   1  95   1   0|   0   164k|1402  3386 
  8   1  91   0   0|   0     0 |1572  3090 
 30   3  67   0   0|   0    32M|2184  3820 
  9   4  87   0   1|   0    37M|1806  3601 
  6   1  93   0   0|   0     0 |1789  3752 
  4   1  88   2   5|   0   104k|1500  3232 
  5   1  71  23   0|   0     0 |1668  3397 
```

It's nice how even interrupts and context switches went down.

**Comment by zlatinb** [comment]
Great!  I think this exhausts the low-hanging fruit.  Of course if you would like to continue optimizing I'm open to it, and especially curious how sharing 120K files will behave on your system.  If not, let me know and I'll close this ticket.

**Comment by zetok** [comment]
I think that it can be closed. As for the 120k files, I won't be testing it today, if something interesting shows up when testing that use case I'll open a new issue.
