### ISSUE TITLE
Need support for 1280x720

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#116]
Hey. I thought I would come say Hi on Christmas eve. You kind of triggered me with your Twitter post ;)

But I cant. For some reason MuWire is the only App that does not display full screen. There's a part at the bottom that does not display regardless if I put the buffer to full-screen. Therefore, I cant do much. 
Also, the name of MuWire. Why is it showing up as `com-muwire-gui-LinuxLauncher`? Im running the AppImage.

Well, Merry Christmas zlatinb. Which you well.

For reference: [EXWM](https://github.com/ch11ng/exwm)
$ xrandr --listmonitors | grep -v Monitors
 0: +LVDS 1280/309x720/174+0+0  LVDS
 1: +HDMI-0 1280/477x720/268+0+0  HDMI-0
![muwire-with-exwm](https://user-images.githubusercontent.com/48020114/147371554-fe1d36b7-f79e-475e-82fc-d295f8abfc74.png)

**Comment by zlatinb** [comment]
Hey @danrobi11  good to hear from you!  

I assume you're running the AppImage.  That uses it's own main class called `com.muwire.gui.LinuxLauncher` and your window manager picks that up as the name.  It's harmless.

I haven't used the EXWM window manager but I'm guessing it's not letting you resize windows?  You can hack your way around that by editing `$HOME/.config/MuWire/gui.properties` and changing the following two values:
```
mainFrameX=1280
mainFrameY=720
```
or whatever X and Y values you wish to use.  On older installs of MuWire the file would be located in `$HOME/.MuWire/gui.properties`.

Let me know if that works and merry Xmas!

**Comment by danrobi11** [comment]
Well, I did not expected support on Christmas eve. Very nice of you. looks like its a EXWM issue. Everything works fine with `xfce`. Whatever value I set it to, I get a blank screen with EXWM. Therefore, I'll have to play with EXWM/xrandr resolution. Sorry for the trouble. I'll see you soon in MuWire ;) Closing.

**Comment by zlatinb** [comment]
Regarding the blank screen, take a look at this wiki page https://github.com/zlatinb/muwire/wiki/Issues-with-Linux-WMs 

Someone reported that setting the options there fixed their blank window problem.  But that won't work with the AppImage, you would have to use the .zip or build from source.

**Comment by danrobi11** [comment]
Hey. Just saw your new msg. It does not work on my end. Added both `export`. Tried with the `.zip`. Changing value in the `gui.properties` = blank screen. Had to try to change the value cuz the default reso in `gui.properties` was too small. Something `1200x1000`
