### ISSUE TITLE
Muwire needs all openjdk-11 jdk. jdk-headless, jre, jre-headless - on Debian?

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#118]
Hello readme says "You need a JDK version between 11 and 17 inclusive."

On Debian 11 i have installed likely like this:

> /var/log/apt/history.log:Commandline: apt install openjdk-11-jdk
> 
> /var/log/apt/history.log:Install: openjdk-11-jdk:amd64 (11.0.13+8-1\~deb11u1), openjdk-11-jre:amd64 (11.0.13+8-1\~deb11u1, automatic), openjdk-11-jre-headless:amd64 (11.0.13+8-1\~deb11u1, automatic), xtrans-dev:amd64 (1.4.0-1, automatic), openjdk-11-jdk-headless:amd64 (11.0.13+8-1\~deb11u1, automatic), libatk-wrapper-java-jni:amd64 (0.38.0-2+deb11u1, automatic), libxcb1-dev:amd64 (1.14-3, automatic), libice-dev:amd64 (2:1.0.10-1, automatic), java-common:amd64 (0.72, automatic), libsm-dev:amd64 (2:1.2.3-1, automatic), libxau-dev:amd64 (1:1.0.9-1, automatic), xorg-sgml-doctools:amd64 (1:1.11-1.1, automatic), ca-certificates-java:amd64 (20190909, automatic), libx11-dev:amd64 (2:1.7.2-1, automatic), libpthread-stubs0-dev:amd64 (0.4-1, automatic), libxt-dev:amd64 (1:1.2.0-1, automatic), libxdmcp-dev:amd64 (1:1.1.2-3, automatic), libatk-wrapper-java:amd64 (0.38.0-2+deb11u1, automatic), x11proto-dev:amd64 (2020.1-1, automatic)

The updates seems to be large:

![debian-openjdk-updates](https://user-images.githubusercontent.com/6596726/151233972-fdc97029-6b11-4238-b9fa-940d24e8cf8e.png)

Do You think that it is necessary to keep everything what I have installed, or can i remove or stop updating any particular part without breaking Muwire dependency?

**Comment by zlatinb** [comment]
Hi,

You need the JDK only if you want to build from source.  If you want only to run MuWire after it's built (or if you're using the pre-built `.zip` distribution) then the JRE is enough.  You need both the `-headless` and the other JRE package though.

**Comment by slrslr** [comment]
> You need both the `-headless` and the other JRE package though.

from Your whole comment i understand that i need all openjdk packages displayed on my image above, since there is no pre-build package at https://github.com/zlatinb/muwire/releases and so i would be cloning git and building:
https://github.com/zlatinb/muwire/wiki/Reproducible-build
https://github.com/zlatinb/muwire#building

**Comment by zlatinb** [comment]
Hi, a pre-built `.zip` is available at https://muwire.com  which is updated only once per release.
