### ISSUE TITLE
MuWire stalls on startup when verifying files

### ISSUE THREAD

**Issue by zetok** [zlatinb/muwire#12]
MuWire version: 85610cf169dcdf9e745412873c25c7467c6fdd44
Started with `-Xmx1G`

#### Description

After launching, MuWire starts verifying the files, and after verifying some of them, it stalls. No new output on stdout/stderr, no increased number rescanned files, and it's not possible to use the search functionality. GUI is kinda responsive, but it doesn't allow MuWire to be turned off (clicking on the close button does nothing).

I don't know what is the cause, but I suspect that it has something to do with starting with cold disk cache.

**The stall causes `files.json` to be truncated** making MuWire rehash those files after restarting again.

So far, it happened twice.

Total number of files: ~4k
Stall occurred after: 2.6/2.7k files

**Comment by zlatinb** [comment]
In recent versions files.json gets written to every minute.  However, the exact logic is that every minute a list of all shared files get written to a temporary file, then the temporary file gets copied over files.json.
Also, MW does not actually verify any shared files on startup, it only hashes them once and puts them into the shared file index.  That index should be up to a minute old.
Why the stall happens is the real question.  Can you do a `kill -3 <pid>` or `jstack <pid>` when MW is stalled?  That will tell me what the different threads are doing.  
Another thing you can do is enable logging.  To do that copy the file `logging/3_logging.properties` from the source tree to PWD and when launching MW pass the following switch to the JVM: `-Djava.util.logging.config.file=3_logging.properties`.  If done correctly a file called `MuWire.log` will appear in PWD with lots of logging information that may help catch the reason of the stall.

**Comment by zetok** [comment]
Another lockup during start.

`jstack` output: [locked_muwire.txt](https://github.com/zlatinb/muwire/files/3415895/locked_muwire.txt)

After running `jstack` on it and letting be for a while it seems that MW lost all connections to peers and it unlocked itself after that. A few minutes afterwards, and there's still only 1 outgoing connection and 0 incoming.

**Comment by zetok** [comment]
And although it "unlocked" itself, the `files.json` were still truncated. After restarting it again, MW started rehasing files.

**Comment by zlatinb** [comment]
Thanks for the stacktrace.  It points to a very interesting place in the code which I did not expect - the logging subsystem.  To fix the symptom, copy `logging/1_logging.properties` (the quietest log file configuration) to PWD and launch MW with `-Djava.util.logging.config.file=1_logging.properties`.

To understand why this happened in the first place I need to know a bit about how you're launching MW.  I'm guessing you do this from a terminal window?  Is there anything special about that terminal window that would cause writing output to it to block?  Like a limit on the number of characters in the console buffer, or some other such policy?

**Comment by zetok** [comment]
>To understand why this happened in the first place I need to know a bit about how you're launching MW. I'm guessing you do this from a terminal window? Is there anything special about that terminal window that would cause writing output to it to block? Like a limit on the number of characters in the console buffer, or some other such policy?

There's no hard limit on the amount of output, however some throttling might happen due to my setup.

MW is running inside a LXC container, with the output of the process being forwarded by LXC and displayed in a `screen` window to which a ssh tunnel is attached.

LXC – I don't know if it can throttle output.
`screen` – can throttle output when there's really a lot of it due to performance (since screen stores set amount of scrollback).
`ssh` – adds some small amount of network latency, might throttle output.

**Comment by zlatinb** [comment]
> `screen` can throttle output when there's really a lot of it due to performance (since screen stores set amount of scrollback).

I imagine this is what's causing the issue then.  So aside from reducing logging which is what using `1_logging.properties` would do, can you look into increasing the screen buffer?

**Comment by zetok** [comment]
When starting it next time I'll just redirect MW stdout/stderr to a file instead of `screen`, so that the buffering won't be a problem.

**Comment by zetok** [comment]
So far, after a few restarts with `-Djava.util.logging.config.file=1_logging.properties` and stdout/stderr redirected to a file MW didn't stall.
