### ISSUE TITLE
Messages tab: context menu or button to add user to contacts/blocklist/browse files?

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#122]
Do you think it can be handy to add option to browse user's shared files from Messages tab?
For example mouse right click menu when i click some of the messages. Menu is already there but missing the option.
Also may be handy to have menu entry for adding the user to the Contacts / Blocklist (not yet interface to easily remove blocked user).

**Comment by zlatinb** [comment]
Well, I don't want to add too many items to the right click menu.  You can achieve all those things by right-click->Copy Full ID and then either paste the full ID in the search box if you want to browse or in the Add Contact dialog if you want to add as a contact or block.

(Yes I know I haven't fixed right-lick paste in the Add Contact form yet.  It's on my `TODO.md` list in the source tree)

**Comment by zlatinb** [comment]
Update: I fixed copy-pasting into the "Add Contact" box and also added a right-click paste option to the search field.

**Comment by slrslr** [comment]
I have cloned and while my library was loading upon muwire 0.8.12beta2 start, Search tab returned results. I have tried to copy your full ID and paste it to Add contact dialog, it pasted it. But not added any contact and i have noticed that searching no longer returns any results. Library was still loading. Once loaded, i see that the contact was added and search returns the results again. If this should be closed, then close this please.

**Comment by zlatinb** [comment]
Yes, unfortunately loading of the library is pretty much a blocker for any other interaction.  To fix that would require major redesign and rewrite.  How does it behave if you disable throttling of the loading or have you already disabled this?

Closing this issue for now.

**Comment by slrslr** [comment]
>  How does it behave if you disable throttling of the loading or have you already disabled this?

yes, this is already enabled

> library is pretty much a blocker for any other interaction. To fix that would require major redesign

no problem
