### ISSUE TITLE
MuWire lost connection to I2P router and needs to be restarted from time to time

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#123]
Hello,
is necessary MuWire quit when internet connection is interrupted? Other non-Java software i am running does not have issue to re-connect. I see that this time I2Pd [on my Linux was code=killed, signal=SEGV](https://github.com/PurpleI2P/i2pd/issues/1738).

Also maybe this "lost connection" message is not translatable on https://www.transifex.com/otf/muwire/

**Comment by zlatinb** [comment]
Hi, for now MuWire will need to exit if it loses connection to the I2P router.  I know it's inconvenient and plan to change that in the future, but it's going to be a big rewrite so it's not going to happen soon.

The two strings `LOST_ROUTER_TITLE` and `LOST_ROUTER_BODY` should now be on transifex.  Thanks for reporting!

**Comment by zlatinb** [comment]
Ok, it turned out to be easier than I thought.  Please try the latest from git - MuWire will not exit when it loses connection to the I2P router but instead keep trying to reconnect.  After it reconnects all should resume functioning.

**Comment by slrslr** [comment]
Good news 👍, after i have restarted the I2Pd service on my Linux, MuWire reported:
"Make sure the I2P router is running ..." OK
I have NOT clicked OK to see that MuWire reconnected anyway because i could see file transfers continued on background. So it seems to be working, unless you have put the limit on number of router re-connection attempts.
