### ISSUE TITLE
Issues on Messages and Composer

### ISSUE THREAD

**Issue by bluebuffy** [zlatinb/muwire#133]
Hi,
i find this bug:
Inbox,outbox, sent not uses the complete field 
![image](https://user-images.githubusercontent.com/80784066/162177895-df384a7a-9d0c-4f6d-9968-7617c63a34d7.png)

other issue when start to compose a mail the composer starts at bottom right and not in center of the window and its to big
![image](https://user-images.githubusercontent.com/80784066/162179924-cf886671-2565-421f-88f2-419103249d67.png)

**Comment by bluebuffy** [comment]
the drag and drop fields for contacts and files takes to much wasted space, for me the composer is not userfriendly, it needs a bette design and it doesnt fit on my notebook screen. the default weight/height must be smaller
![image](https://user-images.githubusercontent.com/80784066/162180528-f22010d4-4a95-4bc8-9da4-4c559772ff2e.png)

**Comment by bluebuffy** [comment]
the drag and drop fields for contacts and files takes to much wasted space, for me the composer is not userfriendly, it needs a better design and it doesnt fit on my notebook screen. the default weight/height must be smaller
![image](https://user-images.githubusercontent.com/80784066/162181820-2266bc47-ea5f-4895-b80a-5d488fdb9e1e.png)

**Comment by bluebuffy** [comment]
i wish a better composer 
![image](https://user-images.githubusercontent.com/80784066/162184514-91f894d9-4947-49c7-8646-95b2a75f8084.png)

![image](https://user-images.githubusercontent.com/80784066/162186199-8f459c14-b31e-4c34-8ae9-81543eb7697e.png)

**Comment by zlatinb** [comment]
Hi,

I fixed the centering issue and reduced the size of the window a little.  The next release 0.8.12 is due in less than two weeks, so I won't do any big changes until afterwards.

A better compose dialog will need some analysis.  Probably something based on Markdown?  It has to be privacy-friendly.

**Comment by bluebuffy** [comment]
> A better compose dialog will need some analysis. Probably something based on Markdown? It has to be privacy-friendly.

yes formatting was nice but first i wish better method to select contacts for send it.

idea like contacts list on left side like how in thunderbird and to fields which takes not much space

- Contacts sidebar (for easy add some one to send a message)
- To field (which takes less space)
- Auto complete feature for to field ( search for nickname then it takes the right contact)

im not sure if this doable in java
![image](https://user-images.githubusercontent.com/80784066/162205011-6dbac8dc-8317-4b0e-9e8a-3a2f3726abe8.png)

**Comment by bluebuffy** [comment]
Another issue on Messages, message Widget not visible on every Start
![image](https://user-images.githubusercontent.com/80784066/163564333-4e310cb6-f27d-477b-a14f-080983d9620c.png)

normaly it must look like this:
![image](https://user-images.githubusercontent.com/80784066/163564586-f0d427b4-1ff5-4fc1-aa96-9dda597a34af.png)

- Message widget needs centered
- File widget minimum size when it contains files else hide it by default

**Comment by zlatinb** [comment]
I'm really not sure why the message widget is not showing.  It hasn't happened to me.

Making the file widget minimum size can be done, I'll try to have it for the next release.
