### ISSUE TITLE
Bug in 0.8.12 - Searchwindow

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire#138]
I just installed 0.8.12 final: the search tab has some problems.
Enter search term, finds sources, lists users.
But when you click a user, nothing is shown. Even when I click me in the results list nothing hapens, it seems to block something when you do a first click on list item from the results list.
I can switch back to the download tab and everything works there, can click everything, ui is updated, downlods are running without problems.

update:
If you click "table" option it shows the files but the results list above with the users is still f* up: Click other list entries (in the above list with users,...) the previous clicked entry is still higlighted, the new clicked one not or sometimes it is.
There is some ui-update problem here.

downloaded the 0.8.12-zip, running on linux/ubuntu, tried different Skins, makes no difference.
The 0.8.12 betas had not this problem, maybe I didn't use the search in the beta versions, I am not shure.

**Comment by zlatinb** [comment]
I think I know what's going on, but before I do any changes can you try the AppImage on Linux?  Also, which Java are you using with the .zip?

**Comment by JamesOlvertone** [comment]
Oh now I get the reason: 

Tired different jdk versions:

Oracle JDK:
17.0.2-oracle : problem
17.0.3-oracle : problem

Open-JDK:
11.0.12-open : no problem
17.0.2-open:  problem

Bellsoft Liberica:
17.0.3-librca: problem

Seem that version 17 of the jdks have this prob.

**Comment by zlatinb** [comment]
Ok, for some reason it is not respecting an `--add-opens` option which is passed to Java from the MuWire start script.

Take a look at the `bin/MuWire` script where you unzipped MuWire-0.8.12.zip.  There should be a line that starts with `DEFAULT_JVM_OPTS`.  Can you copy-paste that line here?

**Comment by JamesOlvertone** [comment]
You are right, my start up script is based on an older relase and never changed it.
I did always a rough overview but missed the new Additions:
"--add-opens" "java.base/java.util=ALL-UNNAMED" 
"--add-opens" "java.desktop/javax.swing.tree=ALL-UNNAMED"

This works now with jdk 17.0.3 oracle.
