### ISSUE TITLE
Contacts and Subscriptions sorting: name sort groups by capitalization

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#140]
Sorting in the Contacts and Subscription lists first sorts all names starting with capital letters then followed by all names with lowercase.

**Comment by zlatinb** [comment]
I need to go through all the places where strings are being sorted and make sure the sorting behavior is consistent.  It will likely take some time...

**Comment by Searinox** [comment]
Could help if you make the sorting policy some static shared object and pass it to all instances of sorting.

**Comment by zlatinb** [comment]
I haven't gone through every place a string gets sorted, but for places where names get sorted the commit referenced above should be sufficient.  Pls grab a [CI build](https://github.com/zlatinb/muwire/actions/runs/2398659998) and if you're satisfied close the issue.

**Comment by Searinox** [comment]
Okay, it's also working in the search tab. All good.
