### ISSUE TITLE
Blank white window after setup wizard

### ISSUE THREAD

**Issue by keystroke3** [zlatinb/muwire#141]
I am on Arch Linux with bspwm. I installed MuWire through the AUR first and ran through the setup wizard. It then switched to a blank white window when it setup was done. I tried the app image with the same result, only I don't go through the setup wizard. I even tried the zip version but that had the same results. I had java 18 installed, and tried swapping it with 17, and 11 but those didn't work. A tray icon appears in the tray, and when I try closing the window, I get a prompt to close to tray or exit entirely.

I am also using i2pd with i2cp enabled on port 7654

```uname -sro
Linux 5.17.9-arch1-1 GNU/Linux
```

``` java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10)
OpenJDK 64-Bit Server VM (build 11.0.15+10, mixed mode)
```

**Comment by zlatinb** [comment]
I'll reach out to the Arch packager because this seems like an issue with the window manager.  Take a look at this [wiki page](https://github.com/zlatinb/muwire/wiki/Issues-with-Linux-WMs) for some suggestions that work on some Linux WMs.

@dbermond can you take a look?

**Comment by dbermond** [comment]
Does not seem to be a packaging issue with Arch.

What is your desktop environment? Xorg? Wayland?

Java applications are known to have some issues with certain window managers. Suggestion is to try other desktop environment / window manager and see the results. You can also try to apply one of [these fixes](https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing).

**Comment by keystroke3** [comment]
@zlatinb I have tried setting the variables as stated in the linked wiki. No difference.
@dbermond I am using Xorg. Your suggested link worked. I set `wmname` to `compiz` and it worked. I tried reinstalling and running the AUR version and it works from when launched from Rofi, so no terminal launch required. Thanks for the quick response and resolution. Feel free to close the issue.

**Comment by zlatinb** [comment]
Thanks you for reporting this @keystroke3 and thanks to @dbermond for the helpful links.  I've updated the MuWire wiki page as I'm sure someone else will run into the same problem.  Closing this issue now.
