### ISSUE TITLE
Edit Profile: Avatar flashes for one moment then disappears

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#144]
Adding and viewing profile avatars appears to work fine. However, when viewing your own avatar via the Edit Profile button, it seems to appear for only one moment then it disappears from the window. Persistence is okay and this appears to be only a display issue in that particular window.

**Comment by zlatinb** [comment]
I've seen this only on Linux, does it happen on Windows too?  I really don't know what's causing it, doesn't happen on Mac at all.

**Comment by Searinox** [comment]
Yes this is happening on Windows as well. It isn't happening in Fetch Profile windows, only in the window where you edit your own profile.

**Comment by zlatinb** [comment]
Not good.  I tried a few quick things but nothing seemed to fix it.  I'll have to take a deeper look.

**Comment by zlatinb** [comment]
I rewrote the way images are painted and now it's working fine on linux.  Please test the latest [CI build](https://github.com/zlatinb/muwire/actions/runs/2440320322) and let me know if it works on windows.

Also, resizing the View Profile window would clear the avatar, that should now be fixed as well.

**Comment by Searinox** [comment]
Tried it in personal profile and also in view profile. Seems to be okay.
