### ISSUE TITLE
Contact selector issues and you dont know who all added for send

### ISSUE THREAD

**Issue by blob2k** [zlatinb/muwire#151]
Hi,
first atttempt its nice but i dont know who is selected for send.
only one empty group box is visible, i see no combobox field for selection (only when i click on empty groupbox)
![image](https://user-images.githubusercontent.com/80784066/174354854-1b75da79-4093-4441-b6db-236e222a271f.png)

it would be nice like how in email composesr who are the contacts which i selected add extra view list for To:
![image](https://user-images.githubusercontent.com/80784066/174354598-5660bf29-7a53-45a1-8452-f346d8726f0b.png)

and contact list on left side would be nice too
![image](https://user-images.githubusercontent.com/80784066/174355513-44dc7084-d903-497d-8faa-327937c186e3.png)

**Comment by zlatinb** [comment]
start typing in the selector box and it will filter your contacts

**Comment by zlatinb** [comment]
The problem is somewhere in the theme.  I'm rewriting it now and will update the issue once I make sure it works on every theme.
