### ISSUE TITLE
A few notes on the Profile window

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#152]
When the Profile window is opened by going to Contacts -> right-click -> View Profile, the profile window is immediately moved behind the main application window.

Furthermore, would it be possible to see trust status in the window, and disable the Add Contact button for people already in contacts, and the Block button for people already blocked?

**Comment by zlatinb** [comment]
I'm afk for a few days but I'll take a look at why the window is hiding behind the main frame soon.

Disabling the relevant buttons should be easy to do.

**Comment by zlatinb** [comment]
Hi, I couldn't reproduce the View Profile window showing behind the main frame on my Windows 10 VM, but in the commit referenced above I've added an explicit request for focus.  Can you try this [CI build](https://github.com/zlatinb/muwire/actions/runs/2541738180) and let me know if it helps?

I'll get to the button disabling soon.

**Comment by Searinox** [comment]
That worked, the window no longer goes behind.

**Comment by zlatinb** [comment]
Please try this [CI build](https://github.com/zlatinb/muwire/actions/runs/2556145259) for the remaining features requested in this issue.

**Comment by Searinox** [comment]
Working well.
