### ISSUE TITLE
[Feature Request] "Neutral" button

### ISSUE THREAD

**Issue by ScriptTiger** [zlatinb/muwire#17]
Currently in the query frame of the "Searches" tab after you enter a query there is only a "Trust" and "Distrust" option, forcing one to jump to the "Trust" tab to "Mark Neutral." I'm sure everyone has their own style and considerations when forming their web of trust, and marking someone as neutral could be just as important as trusting or distrusting someone.

For example, maybe someone has been trusted for a while, but all of a sudden something happens which causes you to reconsider their trustworthiness, but not necessarily distrust them all together. Maybe later on you find yourself using them as a source of content pretty regularly and decide to trust them again. However, if you distrust them, their content would never show up at all and you would never be able to reconsider them.

Like I said, it's all a matter of style and personal preference, but just thought maybe that fits there since that area only has two buttons anyway and it's not like it would cramp anything by making it complete and more convenient.

**Comment by zlatinb** [comment]
Sure why not.  Will put it on the list for next release

**Comment by zlatinb** [comment]
Implemented in referenced commit, please test

**Comment by zlatinb** [comment]
Released in 0.4.14
