### ISSUE TITLE
Is muwire.com dead?

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire#176]
First a warning about security (not safe ... )
Go there anyway:
This page isn’t working
muwire.com didn’t send any data.
ERR_EMPTY_RESPONSE

Tried again:
This site can’t be reached
muwire.com’s server IP address could not be found.

Try:
Checking the connection
Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED

**Comment by zlatinb** [comment]
The MuWire project is shut down.  If anyone wants to keep it going instructions are here on the wiki and the domain is for sale, but I do not accept crypto.

**Comment by peterholthoffman** [comment]
@zlatinb — I hope you don't mind my asking but why did you decide to shut down the project? Thank you!

**Comment by zlatinb** [comment]
@peterholthoffman I will not discuss the reasons why it is shutdown, and they would not be on-topic for GitHub anyway.

**Comment by claudevms** [comment]
How much are you willing to sell the domain for? 
Thank you.

**Comment by zlatinb** [comment]
Whatever price the GoDaddy registrar suggests.  Last time I looked it was around 7k dollars.  Contact me at my email zlatinb at gmail.com if you are interested.
