### ISSUE TITLE
[Feature Request] Content Control Panel Features

### ISSUE THREAD

**Issue by ScriptTiger** [zlatinb/muwire#18]
Just a couple quickies for the Content Control Panel.

1. A "Clear" button next to the "Refresh" button to wipe hits for the currently viewed rule. Currently the only way to do this is by deleting a rule and then re-adding it.

2. Currently the "Refresh" button deselects whatever rule you were looking at and refreshes the pane. I think it would be nice to refresh the pane and keep the previously selected rule selected so you can see the new hits for that selected rule without having to reselect it again after a refresh. More often than not if you've already selected a rule and hit the "Refresh" button, you're curious about the new hits for the rule you're currently looking at.

**Comment by zlatinb** [comment]
Both should be doable, will put them on the TODO list

**Comment by zlatinb** [comment]
Both are implemented in latest master, please test

**Comment by zlatinb** [comment]
Released in version 0.4.15
