### ISSUE TITLE
Feature Request flatpak

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#20]
Hello zab_
Request for the non-technical users.
MuWire as flatpak would be nice. 
Flatpak are popular and user friendly to install
I2pd is already available as flatpak.
It would also be a good advertisement to have MuWire on flathub.
Sharing files, torrenting, thats popular. I2pd and MuWire would be a good mix on flathub

**Comment by zlatinb** [comment]
I need to look into flatpak, maybe it's a good idea.

Right now for non-technical users I have an AppImage at https://muwire.com

**Comment by danrobi11** [comment]
> I need to look into flatpak, maybe it's a good idea.
> 
> Right now for non-technical users I have an AppImage at https://muwire.com

Hello
Is the appimage be working with i2pd?
Thanks.

**Comment by zlatinb** [comment]
The appimage doesn't need i2pd; it already contains a (java) router.  But if you want, you can make it work with i2pd by editing the `$HOME/.MuWire/MuWire.properties` and setting the `embeddedRouter` setting to `false`.

**Comment by danrobi11** [comment]
@zlatinb 
Oh, the i2p router is already embedded in the MuWire appimage. Nice! Thank you.

**Comment by danrobi11** [comment]
@zlatinb 
MuWire is so awesome. Great work. Thank you very much for MuWire.
The world needs to know about it. Im trying to share it as much as possible. 
I really hope you'll add a flatpak version, that would really help exposing MuWire.
Please consider a donate link through Liberapay with credit card and/or cryptos option.
Thanks again for MuWire.
