### ISSUE TITLE
Firewalled

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#22]
![MuWire firewalled](https://user-images.githubusercontent.com/48020114/68181576-ec22e380-ff65-11e9-845d-a0596b4ece72.png)
Hi
I got the same issue i always had with i2p 'firewalled'
I dont understand, my Gufw firewall incoming/outgoing both on allow and same if Gufw is off.
Lubuntu 18.04 lts
Also, when i 'trust' someone, what this means? And when i subscribe to someone what does this means? 
Thanks

**Comment by zlatinb** [comment]
I don't know about Gufw, but have you tried restarting MuWire?  You may want to ask the specific question on https://reddit.com/r/i2p , someone with Gufw experience may help you.

To your other questions:
* When you trust someone you add them to a special list; if you trust enough people you can turn on "Trusted Mode" which means you will connect only to the people you've trusted. 
* When you subscribe to someone you've trusted, you will get updates from them about who they trust or distrust.  You can then review the updates and if you want you can make changes to your trust lists.

**Comment by danrobi11** [comment]
Ok, thanks for the answer. I'll try to get some help from i2p for my firewall issue. L8r @zlatinb

**Comment by danrobi11** [comment]
Ok found the fix
I was behind modem firewall
Fixed with DMZ option in the modem
![MuWire network status OK](https://user-images.githubusercontent.com/48020114/68517626-5bdeea00-0256-11ea-98b1-47b8a0e9d25a.png)
