### ISSUE TITLE
Speed transfert is too slow (Solved)

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#23]
The faster i've seen for a single file to transfert for a few seconds its about 30 kb/s 
- Im outside of the modem firewall(DMZ)  
- iptaples INPUT ACCEPT, FORWARD ACCEPT, OUTPUT ACCEPT
- GUFW in Allow, out Allow
I dont think i can be more open than that.
- MuWire inBw=135000, outBw=16000
Heres an average status example: 
![MuWire transfert speed](https://user-images.githubusercontent.com/48020114/68532062-554c8300-02e7-11ea-836b-37c4a074daa7.png)

I also did a video. Uploaded it in MuWire. Hash: lOFEB8UJCJhJY6YM8B8N5f70iLKmCMpgRII~9RathI4=
i2p side seems fine. Network status at ok and a lot of tunnels. 
 I wonder if the speed tranfert are slow because users might be firewalled?
Is MuWire suppose to be able to transfert file faster than this?
Thanks.

**Comment by danrobi11** [comment]
@zlatinb Are you firewalled? Modem maybe? Its slow

**Comment by zlatinb** [comment]
MuWire uses the I2P streaming library for file transfer.  Speed is entirely dependent on the performance of I2P and it's streaming lib.

The I2P developers are actively working improving that, as well as the initial bootstrap time.  It's going to take a while for improvements to filter down to MuWire, but there should be some as soon as January.  As soon as the next I2P version is released, I will make a new MuWire build that uses it.

While it won't change the total download time, you can play with the download smoothing interval (it's configurable in the settings).  That will give you an idea of how variable the raw speed of I2P is.

**Comment by zlatinb** [comment]
Yes I'm downloading the video.  Btw in the future it's better to post the hash of the file you want to share, that way I know I will fetch the exact file you have in mind.

**Comment by danrobi11** [comment]
> Yes I'm downloading the video. Btw in the future it's better to post the hash of the file you want to share, that way I know I will fetch the exact file you have in mind.

Got you.



> MuWire uses the I2P streaming library for file transfer. Speed is entirely dependent on the performance of I2P and it's streaming lib.
> 
> The I2P developers are actively working improving that, as well as the initial bootstrap time. It's going to take a while for improvements to filter down to MuWire, but there should be some as soon as January. As soon as the next I2P version is released, I will make a new MuWire build that uses it.
> 
> While it won't change the total download time, you can play with the download smoothing interval (it's configurable in the settings). That will give you an idea of how variable the raw speed of I2P is.

Thats so unfortunate. MuWire is so awesome. Theres nothing like MuWire (that i know of)
Is it possible to implement MuWire as a standart torrent client (over vpn) with the exact same features?
That would become popular really fast.
Thanks for the trouble and the answers. Have a good weekend.

**Comment by zlatinb** [comment]
> Is it possible to implement MuWire as a standart torrent client (over vpn) with the exact same features?

No, absolutely not.  MuWire relies heavily on the cryptography and design of I2P.  It's just not possible to achieve the same trust model without the assurance of digital signatures that I2P gives.

It might be possible to mimic what MuWire does by adding signatures to a torrent client over VPN, but it would be a massive effort.

**Comment by danrobi11** [comment]
- No, absolutely not. 

Ok, i see. Thanks again for your time and support. I'll close this issue now. C u l8r @zlatinb

**Comment by danrobi11** [comment]
Hello. Im running the i2p browser https://geti2p.net/en/browser
Seems like the i2p browser router is a bit faster and participating more.
![i2p browser network status](https://user-images.githubusercontent.com/48020114/68549289-923a7780-03c4-11ea-9f50-fb348cadf207.png)

 I've tried running MuWire whit the embeddedRouter=false but it doesnt work.
'Couldnt connect to i2p router. make sure i2p is running and restart MuWire'
What do i need to run MuWire with the router of the i2p browser?
Thanks.

**Comment by zlatinb** [comment]
The router that is included in the I2P browser has disabled the I2CP protocol.  I2CP stands for "I2P Client Protocol" and is what MuWire uses to talk to an external router.

If you want to run an external router, get the main download package from https://geti2p.net , not the browser.  That has I2CP enabled by default.

They're all the same code inside, so one wouldn't be faster than the other.  However, if you plan on browsing eepsites, using i2psnark torrents and running MuWire at the same time, it's better to run a single I2P router.  So get the main package.

**Comment by zlatinb** [comment]
You can also use i2pd if you prefer, of course.  Just enable I2CP in the options.

**Comment by danrobi11** [comment]
Well, that happened: https://discourse.lubuntu.me/t/cant-login-stuck-at-boot-screen/519
It turns out that we can use the i2p browser with MuWire. I2CP is enabled. But not on same port, its 17654. MuWire is working fine.
I did not test as much as i wanted to. All i know so far is that ip2 network is really weird. Earlier today, under 99min, i had  over 500 participating, was sharing close to 200kb/s with a share ratio of over 10. And now, after 2hrs: 70 participating, sharing about 20/40 kb/s with a share ratio of 0.75. 
At least now i know i can run MuWire with the i2p browser.

**Comment by danrobi11** [comment]
Okay finally
![best i2p network ever2](https://user-images.githubusercontent.com/48020114/68612098-a4dfaa00-04b3-11ea-8ca8-b4a955c27e8f.jpg)
This is with i2p browser. I Never came close to this speed with the ip2 router nor MuWire, even after days of running. Only 7hrs! Outstanding!

**Comment by jeroen7s** [comment]
5-6kb/s is the max i've been able to achieve downloading files from MuWire.
Is that really the limit of the I2P streaming library?
Not familiar with I2P, but if that's the case, even torrenting over the tor network is a gazillion times faster than this.
