### ISSUE TITLE
New Chat questions

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#25]
Hello
Congrats with the new chat option. 
How is chat working?

**Comment by zlatinb** [comment]
A lot like IRC.  Basically you can run a chat server and others connect to you, or you can connect to others who are running a chat server.  (I just found out you can't do both at the same time; will fix that in the next release).  

Once you connect you can for example `/join` a chat room, `/list` existing rooms on the server, or get `/info` about the server like it's address and who is connected to it.

To find out who is running a chat server you need to do a search and if the "chat" checkbox is checked it means you can connect to them.  If you want to keep your chat server private, disable "Advertise chat ability in search results" in the options.

**Comment by danrobi11** [comment]
- Damn, now MuWire gets even more interesting.

This new chat option gives a lot of ideas!
It Would be very useful to have a sort of public chat announcement, that would only display new uploaded files by date etc. That would need another option to let the users decide if they want to announce their new upload in the public chat announcement.
And, of course, a sort of public social media chat is a must. 

Very awesome!

**Comment by zlatinb** [comment]
It's not difficult to integrate sharing of files with automatic posting of hashes to a chat room.  I'll wait a while and see how much use the chat function gets before implementing such thing.

I'm not sure what you mean by "public" chat; if you mean something that can be discovered by everybody then that thing needs to be centralized, and centralization is very much against the spirit and intentions of MuWire.  Of course, nothing is stopping someone from announcing their chat server address in public and becoming popular.  But that needs to be a manual process.

**Comment by danrobi11** [comment]
- 'It's not difficult to integrate sharing of files with automatic posting of hashes to a chat room'
Cool. That would serve as a sort of tracker2.postman.i2p. Users could connect to the public upload announcement chat room, to know whats available to download.
- 'with automatic posting of hashes to a chat room'
Idk about automatic. Letting the users decide if they want their new upload to appear in the public upload announcement chat room.  
- 'But that needs to be a manual process.'
Sounds good.
- I'm not sure what you mean by "public" chat'
Like you mentioned 'like IRC'. A public chat room for every MuWire user to connect and chat. 

Im in your MuWire chat btw.

**Comment by danrobi11** [comment]
Forgot to mention
 'Group Chat'

**Comment by zlatinb** [comment]
I see you on my server, but you need to `/join` a room before we can have a conversation.  Try joining `#muwire`

**Comment by danrobi11** [comment]
Missing chat from trust. 
I dont see a way to start a chat with a trusted user from 'trust'

**Comment by danrobi11** [comment]
Missing chat from trust.
I dont see a way to join a trusted user chat from 'trust'

**Comment by danrobi11** [comment]
Hello
Looks like when someone join your chat and doesnt disconnect it does this: MhoEoGA9jp-FV1yqJxAZL1RPh-ULPnNOid0OpShSOx4=
Over 200 of connection/disconnection. So, i closed the chat and re-started a chat room with the same name '#chat' and you're automatically re-joining the chat. Which make connection/disconnection over and over in the chat.
I had to make a new chat room under different name for this to stop.

**Comment by zlatinb** [comment]
Connects and disconnects are normal and due to conditions in the I2P network.  The chat client is configured to immediately reconnect to the server upon disconnect.

REJECTED happens when someone tries to connect to the same server with more than one connection.  In practice, it takes some time for the server to notice the disconnect.  If a client gets REJECTED it will wait for 1 minute before trying to connect again.

**Comment by danrobi11** [comment]
Zab, nevermind for now the master deleting issue. Too hard to use the chat now.
If you want me to test new commit let me know here

**Comment by danrobi11** [comment]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
I cant connect to you with normal appimage
I've this error
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by danrobi11** [comment]
I cant connect to you with normal appimage
I have this error
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by danrobi11** [comment]
I cant connect to you with normal appimage
I have this error in terminal when trying ./gradlew clean assemble
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by zlatinb** [comment]
When you're building form source you need to either have java in your path or set JAVA_HOME accordingly.  Since you're on a debian-based system, type `java` and install the jdk 11 package (it should be called openjdk-11-jdk-headless or something like that).  That will add java to your PATH and gradlew should work.

**Comment by danrobi11** [comment]
we should go back to mw
i type java and thats the result: bash: java: command not found
I have java 11.0.5 installed. In home i see a .java

**Comment by zlatinb** [comment]
try typing `javac`, that comes only with the jdk.  Alternatively, download a jdk for linux from https;//adoptopenjdk.net , unpack it, then set JAVA_HOME to point to the base directory.

**Comment by danrobi11** [comment]
my chat is running. if you can join, me i cant

**Comment by danrobi11** [comment]
cant connect to you

**Comment by danrobi11** [comment]
connecting / failed over and over.
You, can you connect to me? my server is open

**Comment by danrobi11** [comment]
Closing this.
If any body got any questions or got some ideas about some chat feature for MuWire, feel free to post them here.
