### ISSUE TITLE
Share directory and dismiss unshare (Solved)

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#26]
(You might know already about this)
- Instead of opening a directory if we click on open, it will share the entire directory. Maybe implementing 'share directory' next to 'open' would fix that.
- So i marked the files as unshare. Now, i cant find a way to re-enable them for sharing. I think it should be here, right click on the desired file or directory to dismiss unshare.
 Screenshot hash file: zrRv22lginiwccmz6cYlb3pEZQtNbI4-FDeaolb2W3U=

**Comment by zlatinb** [comment]
Regarding the first issue, I'm using a pre-built Swing component called JFileChooser which implements that behavior.  It would be a lot of work to implement my own file chooser with separate "Share" and "Open" buttons for directories.

For the second issue, you have to re-share the files and they will be gone from the negative tree.  I'm not too excited about making the negative tree editable as that will cause too many mistakes by users.

In general, the best way to manage shared files is via drag-and-drop.

**Comment by danrobi11** [comment]
I've tried that a few times and that doesnt work here. 
I had to re-locate the file in another directory in order to be able to share a unshared file

**Comment by zlatinb** [comment]
ok I'll try to reproduce

**Comment by zlatinb** [comment]
Try with the latest commit pls

**Comment by danrobi11** [comment]
unshared files are not showing up in: advanced sharing/ negative tree.
Nothing in both.

**Comment by danrobi11** [comment]
Files shows up only after uploading a directory

**Comment by zlatinb** [comment]
Right, if you downloaded master you would have the latest commit.

Files appear in negative tree only if they are inside a fully-shared directory.  It's a bit complicated use case, but let's say you want to share an entire directory except for a few files; you can then drag-and-drop the directory and select only the files you want to unshare.  Then those files will appear in the negative tree.

**Comment by danrobi11** [comment]
Ok. Thanks for the fix.
