### ISSUE TITLE
MuWire is loading, please wait...

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#43]
Hello,
yesterday i downloaded the MuWire and after filling the username and download folder, i see "MuWire is loading, please wait" message is there for hours. I remember when internet disconnected when i recovered computer (Windows 10) from sleep, then the interface loaded. But no connections, so i quit it and then start again and same scenario.

i see the .log file, but [it shows the entries from yesterday](https://defuse.ca/b/XHttROLjH7Pu4BEs9AOazv), i possibly need to enable debug mode somehow/how? Thank you

**Comment by zlatinb** [comment]
Hi,
Thanks for the report.  I will need to look at logging at INFO level to find out what is happening.  In the location where you installed MuWire (default is `c:\Program Files (x86)\MuWire`) there should be a file called `1_logging.properties`.  Open that file and change the following line:

```
.level = SEVERE
```
to
```
.level = INFO
``` 

That line is around the middle of the file.

Restart MuWire and there should be a lot more log entries in the MuWire.log file.  Note that there will be some information that you may not wish to make public such as your MuWire nickname.  Let me know if that's the case and we'll think of some way for me to look at the log file without making it public.

**Comment by slrslr** [comment]
@zlatinb thank You, i think i succeeded enabling INFO log mode. [here](https://www.privfile.com/download.php?fid=5ea198c9b7fb4-NjI4) is the log file. The password is your github username... This time i let the MuWire run "only" 30 minutes during which i seen "MuWire is loading, please wait...").

**Comment by zlatinb** [comment]
Thanks, I got the file.  Looks like MuWire was not able to connect to any of the I2P "reseed" servers.  Is it possible it's blocked by the windows firewall from making outgoing connections?  

The reseed servers are:
```
https://netdb.i2p2.no
https://reseed.onion.im
https://i2p.mooo.com
https://i2pseed.creativecowpat.net:8443
https://ressed2.i2p2.no
https://i2p.novg.net
https://reseed.memcpy.io
https://reseed.i2p2.no
https://reseed.i2p-projekt.de
```

If you are able to connect to any of these servers through your browser (ignore the certificate warning, just check if the connection gets established) then most likely the windows firewall is stopping the connections from MuWire.  

Go to `Control Panel > System and Security > Windows Defender Firewall` and select `Advanced Settings`.  Then in the leftmost panel select `Monitoring -> Firewall`.  The "Name" that MuWire will be have there is "**OpenJDK Platform binary**".  See if there is a rule set to Allow or Disallow connections in Outbound direction.

**Comment by slrslr** [comment]
@zlatinb that was the problem. Thank you and sory that i have not noticed on my own.
My firewall used to report new software internet connection attempts. But this time i do not remember seeing any prompt...
After i added "C:\Program Files (x86)\MuWire\jre\bin\javaw.exe" to my firewall within allowed apps, then issue is solved.
It may be more noob user friendly if the app reports the error after some period of time or after it fails to connect all reseed servers.
Like: MuWire was unable to connect reseed servers. Please make sure the C:\Program Files (x86)\MuWire\jre\bin\javaw.exe is not blocked by your firewall.

**Comment by zlatinb** [comment]
Hey, glad it worked out!  Don't forget to change the logging back to SEVERE otherwise MuWire will use up a lot of CPU and disk space.

I've updated the installer on https://muwire.com to identify itself as "MuWire" to the Windows Firewall, so users will be less likely to get confused.
