### ISSUE TITLE
MuWire plugin icon on I2P Java Console is too light to be visible on Light Theme

### ISSUE THREAD

**Issue by eyedeekay** [zlatinb/muwire#46]
It would be helpful if the MuWire I2P Java plugin icon could be darkened or colored in some way. As it stands it is barely visible in the sidebar. I used this slightly altered version to make the link on the console /home page more visible, but if you have an SVG to use of it that might be a better thing to work with:
![muwire](https://user-images.githubusercontent.com/8733713/89858123-56b81e00-db8d-11ea-99f1-5731d9c92f7b.png)

**Comment by zlatinb** [comment]
Interesting, I used the same color that is used for the other icons, and it looks ok on the current light theme here.  Anyway, the source svg is at https://muwire.com/muwire-icon.svg

**Comment by zlatinb** [comment]
Oh nvm I thought you were talking about the eepsites of interests section.  The png that is in the sidebar plugin needs to be part of the plugin ofc.  I'll look into it, unless you want to open a MR on gitlab ;-)

**Comment by eyedeekay** [comment]
Yeah I'll send you an MR later today.

**Comment by zlatinb** [comment]
Merged the MR.  Your GitLab username is not connected to your GitHub username, so it doesn't show you in the contributor's list.
