### ISSUE TITLE
Browse host

### ISSUE THREAD

**Issue by falcogiallo** [zlatinb/muwire#49]
I found a problem using the "Browse host" button
If I click the button to explore a user's share, the window freezes after seconds, buttons unusable, curtain unusable, column orientation unusable, tab close button active but not working.
Generally download of the share list stops around 18% and it is impossible to carry out any other operation.
The PC's cooling fans increase in speed.
From the windows "Task Manager"client is not blocked, but the window that show the share block any action and it's impossible to close it.

**Comment by zlatinb** [comment]
Does this happen on every host you browse or only on specific one?  This looks like there are too many files being shown in the table.  If you do not enable sorting it should behave a little better, although that's not a solution.

I will put an item on my TODO to optimize the handling of search results.

**Comment by falcogiallo** [comment]
I think it happens with everyone.
I can't tell you if it depends on the number of files to be explored because I have never been able to complete an exploration due to the blocking of the window.
To get out of this deadlock the only solution I found was to force closure of the client.

**Comment by zlatinb** [comment]
Hi, I just committed something that helps - I was able to browse someone with 19k files while sorting without any problems.  Can you give latest master branch a try?

**Comment by falcogiallo** [comment]
Master branch? How should I do?

**Comment by falcogiallo** [comment]
I have had other crashes, muwire has always started working again.
I would like to submit some particularities.
1) A high number of files in hashing
2) IP change by the provider or VPN
3) High number of downloads at the same time.
Do you think some of these points may lead to instability?

**Comment by zlatinb** [comment]
I've built a windows installer just for you that contains the fix.  If you do not object to me seeing your IP address on the server log, you can download it here:  https://muwire.com/MuWire-0.7.6-github49.exe 

If you're not on windows or do not want me to see your ip let me know and I will show you how to build from source.

Regarding the other questions, older MuWire versions had problems with too many shared files, but the 0.7 series should handle them just fine.  I don't know enough about VPNs to tell if that is what's causing problems.  High number of downloads shouldn't matter.

**Comment by falcogiallo** [comment]
Ok Installed. Now it seems to work fine, however I continue to test it.
But this release seems to be doing much better than the previous one. the counting of files in share is now correct and seems to connect to peers much faster.

**Comment by zlatinb** [comment]
Glad to hear.  The next release 0.7.7 will be out this Friday and will contain the fix.

Let me know if you have any other questions and when you're happy please close the issue.
