### ISSUE TITLE
Error in logging, should be an info?

### ISSUE THREAD

**Issue by RED29** [zlatinb/muwire#50]
Git this error: 

> ERROR - Cannot find I2P installation in "/XXXX/XXXX/XXXX/MuWire - Will probably be just a router with no apps or console at all!

> Warning - No client apps or router console configured - we are just a router

Shouldn't be both an info? I indeed don't have an I2P installation, only Muwire app, and most people also I think.

**Comment by zlatinb** [comment]
Hi,
I agree this should be at INFO level, but the code that logs these messages is from the I2P router library.  It's not under my control I'm afraid.

**Comment by RED29** [comment]
Ok, thanks for explaining. You can close this issue.
