### ISSUE TITLE
0.8.4 and macOS Big Sur

### ISSUE THREAD

**Issue by RED29** [zlatinb/muwire#52]
I got an security warning, and it seems that I can't skip it by allowing it in the settings... has anyone tried this in the new macOS version?

**Comment by zlatinb** [comment]
The only thing I changed in 0.8.4 from earlier versions is to bundle with AdoptOpenJDK version 15 instead of 14.  Can you try this build: https://muwire.com/downloads/MuWire-mac-java14-0.8.4.zip and let me know if it works?

**Comment by RED29** [comment]
Hi @zlatinb its indeed something to do with AdoptOpenJDK version..
The java version 14 gives also a security warning, but you can open it anyhow and it works.
The version 15 gives a security warning but you can't open it. It looks like a crash, it never shows up.

**Comment by RED29** [comment]
Its version 14 also good to use? Or do you suggest not to use it?

**Comment by zlatinb** [comment]
Yes version 14 is good to use.  In fact I just made it the default download for Mac.  I'll go back to building with Java 11 on Mac with the next version.

**Comment by zlatinb** [comment]
0.8.5 is out, I've reverted to using Java 11.  Closing this issue for now, if there are still problems please open another one.
