### ISSUE TITLE
Fails to build on Manjaro Linux - gradle 7.0-1: Configuration with name 'compile' not found

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#55]
Hello, is this right place to report this? I have issue building muwire-git: https://github.com/gradle/gradle/issues/17051
What should i try please?
@zlatinb

**Comment by zlatinb** [comment]
MuWire doesn't work with Gradle 7 yet.  Can you try with an earlier gradle version?  Ideally you would the wrapper which fetches Gradle 5.2.1, but I've heard Gradle 6 works too.

Also, building with JDK 16 doesn't work yet (as it requires Gradle 7), build with JDK 11.

**Comment by zlatinb** [comment]
Hi, as of the latest commit MuWire builds fine with Gradle 7.  Please give it a try and if it works close the issue.  (Should also work with Java 16)

**Comment by slrslr** [comment]
I have just tried to build again,

$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

$ gradle --version
Gradle 7.0
Build time:   2021-04-26

it failed to load/resolve some classes:

```
> Task :gui:compileGroovy
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :gui:compileGroovy
startup failed:
/var/tmp/pamac-build-usrname/muwire-git/src/muwire/gui/griffon-app/views/com/muwire/gui/OptionsView.groovy: 24: unable to resolve class java.awt.Taskbar
 @ line 24, column 1.
   import java.awt.Taskbar
   ^
```
if necessary, full output is [here](https://bin.disroot.org/?67b64bc0a307a494#Ha82NmmwaSuk5wYAeY8y9Nra71LSQkUh1RgxUjQSgqGg)

so the issue is in Java (openjdk version "1.8.0_292") version?

when i search for oracle using Manjaro Linux package manager, i see [this](https://bin.disroot.org/?6a6a2037741446e6#FEGqHrcsdEiJdFJ9jgkKn3atwMVVXXwCCX3WYS5oFDpZ). When i search for openjdk, then [this](https://bin.disroot.org/?5e9b3b447d51605e#5n6SaSbhDfLjp3NfwmkBJSuhwGEqYXLNqpc45kJvoEU3).

Please what can i try?

**Comment by zlatinb** [comment]
Hi, get the `jre11-openjdk` package from Manjaro.  It should build with that.

**Comment by zlatinb** [comment]
Correction, `jdk11-openjdk`.

**Comment by slrslr** [comment]
> `jdk11-openjdk`.

result:
```
Installing jre11-openjdk-headless (11.0.11.u9-1)...                                                                                                                                      [1/3]
Default Java environment is already set to 'java-8-openjdk'
See 'archlinux-java help' to change it

Installing jre11-openjdk (11.0.11.u9-1)...                                                                                                                                               [2/3]
Default Java environment is already set to 'java-8-openjdk'
See 'archlinux-java help' to change it

when you use a non-reparenting window manager,
set _JAVA_AWT_WM_NONREPARENTING=1 in /etc/profile.d/jre.sh

Installing jdk11-openjdk (11.0.11.u9-1)...                                                                                                                                               [3/3]
Default Java environment is already set to 'java-8-openjdk'
See 'archlinux-java help' to change it
```
```
$ archlinux-java status
Available Java environments:
  java-11-openjdk
  java-15-openjdk
  java-8-openjdk (default)

$ sudo archlinux-java set java-11-openjdk
```
```
$ pamac build muwire-git

...
> Task :gui:compileGroovy
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
...
==> Starting check()...

> Task :core:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/usrname/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.4/e2a8bbcffa3faaa81facb7e2981acf9802c4c8c2/groovy-3.0.4.jar) to method java.nio.DirectByteBuffer.get(byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 50s
...
```
if needed full build output [here](https://bin.disroot.org/?4afdd137a98013c3#BVa3VFmu4g17psFGg1Q4FBBn3pu4ZoonzWzMoiq9uMqS)

```
$ muwire
Jun 01, 2021 2:01:39 PM java_util_logging_Logger$info$0 call
INFO: No config file specified, so turning off most logging
Jun 01, 2021 2:05:22 PM java_util_logging_Logger$log$7 call
SEVERE: couldn't initialize core
net.i2p.client.I2PSessionException: [MuWire(OPENING)]: Cannot connect to the router on 127.0.0.1:7654 and build tunnels

$ pamac install i2pd
$ systemctl enable i2pd;systemctl start i2pd;systemctl status i2pd
... --conf=/var/lib/i2pd/i2pd.conf ...
Started I2P Router written in C++
```
that .conf says path is not accessible, because it seems to be symbolic link to /etc/i2pd/i2pd.conf and when searching that file for muwire expected port 7654, it shows this as I2CP port and the line is commented out/disabled (# port = 7654), so i removed "# " and ran "systemctl restart i2pd", muwire still unable to connect "127.0.0.1:7654"

[i2pd log](https://bin.disroot.org/?7a4f95af0c274a3d#91zQXWSHKamdw8Z1bbQtugTZLQVwfNruZdMHD5eUmRAw) no error except 9151 port

[MuWire wiki](https://github.com/zlatinb/muwire/wiki) does not seem to contain i2p or port phrases in it

please what to try?

**Comment by zlatinb** [comment]
Glad to hear!  Make sure you use the latest version of I2Pd because earlier versions had a bug where MuWire would disconnect frequently from the I2Pd router.

If you're happy please close this ticket.
