### ISSUE TITLE
Limit CPU utilization during Library building/hashing?

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#57]
Thanks for this nice software. Just a small feedback. It can take hours to hash terabytes of data. And during this the CPU is maxed out (htop shows that the Muwire's java process using 700% of the CPU thread), it can cause some issues to other apps like a VLC (utility "nice" not worked for it to stop lagging the playback). Just wanted to ask if this can be easy for you to make muwire not to utilize 100% of the CPU, but maybe such feature can get complicated and, so in that case close this ticket.

**Comment by zlatinb** [comment]
It's easy.  I'll add a setting to limit the number of CPU cores used when hashing and post here how to use that setting.

**Comment by zlatinb** [comment]
@slrslr please try rebuilding MuWire from the latest commit.  You will see a new option how many CPU cores to use when hashing.  Change the value to whatever you like, then restart MuWire.  

Let me know if it works and if you're happy close this issue.

**Comment by slrslr** [comment]
@zlatinb i will do it, currently the app is not responding for like 5 hours, before stopped responding, the count of hashing completed files no longer was growing. The process list shows quite high CPU utilization and very low disk activity in kilobytes. I think i should kill it? File count in ~/.MuWire is not increasing.

**Comment by zlatinb** [comment]
Yes, please kill the process.  

I think it's most likely ran out of heap memory.  By default the heap is limited to 256mb RAM, which should be good for about ~100,000 shared files.  If you have many more than that you will need to increase the memory that MuWire is allowed to use.  But let's first see if the latest change achieves what you originally wanted.

**Comment by slrslr** [comment]
I have tried to let package manager to find updates in AUR package muwire-git:
yay -Syu --devel
pamac upgrade -a --aur --devel
but not found any update. So not knowing how to do it better (saving internet bandwidth and downloading only changed files, this was built using package manage and AUR repository), i have downloaded all things again and followed commands in readme file:

cd ~/apps/;git clone https://github.com/zlatinb/muwire.git;cd muwire
./gradlew clean assemble
./gradlew gui:run

i see it is using different username inside muwire status bar than the build from AUR repository (and even when i launch the AUR build it seems to reset username to MuWireUser@. App responding, low CPU usage, but on Library tab, when it reach 60+K of files shared and stop counting, the CPU load increase to like 85% from like 15% and app stop responding (similar to what happened before i killed the muwire build via AUR).. (i ended up me being unable to switch to other app), so i killed it again.

Yes, i have found option to limit the hashing to half of the CPU threads (seems by default) so that looks good, so before app frozen, i have tried to input another files for sharing, it was folder with around 200K files, total maybe 50GB+ and the result was that the total CPU load during hashing was not like 95% but like 80%, the java process with highest load was not 700% as previously, but around half of that (ye,s i have half CPU threads set), other java processes was using like 30-90% each, and there was maybe 8 such processes.

If you can suggest what to try, mainly regarding that app freeze, please let me know (I am not sure how to increase heap 256M). Thank you

**Comment by zlatinb** [comment]
Ok, you have a lot of files, so you will need to increase the memory quite a bit.

```
# First, let's get a fresh copy.  You can skip this step
git clone https://github.com/zlatinb/muwire
cd muwire
./gradlew clean assemble

# Now, unzip the .zip distribution
mkdir somewhere
cp gui/build/distributions/MuWire-0.8.7.zip somewhere
cd somewhere

# Now, increase memory - you can edit the file manually if you want, or just use "sed"
sed -i "s/Xmx256M/Xmx1024M/g" MuWire-0.8.7/bin/MuWire

# Launch MuWire
sh MuWire-0.8.7/bin/MuWire
```

I think the reason why your nickname reverted to "MuWireUser" is because MuWire could not shut down gracefully and was killed.  That's not a big deal, you can edit `~/.MuWire/MuWire.properties` and change the nickname there.

Another thing - I suggest you reduce the number of threads even more, maybe 1/4 of the number of cpu cores.

**Comment by slrslr** [comment]
I did that. I increased memory from 256 to 1024, ran "sh MuWire-0.8.7/bin/MuWire" with 1/4 of the number of cpu threads., tried to remove the folder with around 200K files, now the app is hardly responding, yet the CPU is utilized minimum and disk too. Process manager shows only 2 java processes with 2x2.4MB/s and this is SSD so i am not sure where is bottleneck in the app. After 10 minutes of the interface not responding the CPU load increased to the values seen when there was no CPU limit and disk bandwidth is also high, so possibly hashing happen, yet the interface continue not responding. I am not sure if/how is applied CPU limit but Configuration page shown number 4 which is 1/4 of the 16 threads. i was running recent clone: ~/apps/gitclonemuwire/MuWire-0.8.7/bin/MuWire
If you wish, let me know what to try.

**Comment by zlatinb** [comment]
I think the problem is that you removed the folder with 200k files before it finished hashing.  That will confuse MuWire.  I think the only thing we can do now to get all your files to hash is to start hashing from the beginning with 1/4 threads and increased memory.  To do that:

1. Stop MuWire if it's running, or kill it if it doesn't respond
2. Open `~/.MuWire/MuWire.properties` in an editor and make sure that your `nickname` is correct and that `hashingCores` = 4.
3. Delete the folders `~/.MuWire/files` and `~/.MuWire/directories`
4. Start MuWire again.  It will show 0 shared files.
5. Add the folders you want to share again.

I'm sorry about this, and I appreciate your patience.  Hopefully we'll get it to work this time.

**Comment by slrslr** [comment]
Thank you, yes, i did that. The **CPU limit feature seems to be working**. 👍 It is not like i would see maxed out certain threads, but it is distributed. one process like 300% and maybe 6 other are 30-90%. When the default limit of the CPU threads number is 1/4 of available ones, i think it means that this will only prevent CPU over-utilization/lags, if average user CPU utilization without MuWire is up to ~35% meaning that i think MuWire is not using 1/4 but maybe 1/2. Personally, i think i would set mine to 2 threads out of 16 instead of 4 out of 16, even my utilization without MuWire is around <40% the 16 threads.

The Status/System status shows 1GB available memory. The usage started at around 150MB when started hashing. After 6 hours when hashing is long time complete (several tens of thousand files) is 200-800MB.

**I have just started experiencing UI lag again last 10 minutes UI is not responding, count is beyond 75K files shared(possibly above 6TB?)** CPU usage is around 6 threads and disk usage is significant at times.

**Comment by zlatinb** [comment]
@slrslr with the latest commit you no longer need to restart MuWire if you change the number of CPU cores to use when hashing.  Please give it a try when convenient.

**Comment by slrslr** [comment]
> Keep an eye on it, especially the memory usage

I did, it is 650-840MB, seen 890MB maximum in last 24 hours. 250MB static limit seems too insufficient and out of reach for a regular user to tune it with a confidence.

So i have updated git files:
cd /path/to/git/muwire;
git remote add origin "https://github.com/zlatinb/muwire.git" 2>/dev/null;git pull origin master
./gradlew clean assemble
copied .zip file as mentioned, extracted, replaced memory variable, launch via: sh MuWire-0.8.7/bin/MuWire
To test things, i have tried to add directory with quite alot of files, it is 15 minutes and interface is still not responding. and CPU is maxed out (htop shows like 12 java processes of muwire, each is around 50-80% CPU usage and main top process is even sometimes 1000% usage) even i had 2 CPU threads set in Options. So i can not test now if changing threads will have affect on CPU.

**Comment by zlatinb** [comment]
On the library tab at the top it should say "Hashing X Files" where X should be a number not greater than the number of threads you have configured.  If it says more than that then there must be a bug somewhere.

While MuWire is running, can you open `~/.MuWire/MuWire.properties` in an editor and see if `hashingCores` has the correct value of 2?

**Comment by slrslr** [comment]
Yes, hashingCores=2 in the .properties file. Yet the MuWire not started respinding and it is one hour. Still CPU maxed out same way as described. Fortunately i have Library tab open (even the interface is frozen) and on the top is Hashing: ..filepathhere.. (size KB), i do not see "Hashing X Files", maybe due to frozen UI. What do you suggest?

**Comment by zlatinb** [comment]
The problem must be somewhere else then.  Can you do the following:

1. kill MuWire
2. Change `hashingCores=1` in the `.properties` file
3. Restart MuWire

Let me know if it get stuck again.  Also, please tell me a approximately how many files are in the folder you try to share  - 100,000 or 1 Million or 10 Million etc.

**Comment by zlatinb** [comment]
@slrslr I think the problem is that if there are too many files in a single folder - like 100s of thousands or more - then MuWire may run out of memory.  I just committed a change that will read the contents of large folders more efficiently.

Please change `hashingCores` back to 2, and update from latest git and try adding the big folder again.

**Comment by slrslr** [comment]
It seems that the MuWire was killed by system or itself:

> java.lang.OutOfMemoryError: Java heap space
> Dumping heap to java_pid2787033.hprof ...
> Heap dump file created [1629777958 bytes in 12,392 secs]
> Terminating due to java.lang.OutOfMemoryError: Java heap space
> 

that dump file java_pid2787033.hprof is 1.6GB in size.

previous run with clean exit was 24 hours long and memory usage (shown in Muwire/Status/..) was around 800MB. This shoer run where i tried to add new shared directory, it frozen for a hour+ and then got killed.
The shared dir. i added contained around 300K files worth 300GB.

So i have tried to set: hashingCores=1
and launch MW. Somehow on library tab, the count of shared files was not growing as fast as previously (previously i had more CPU threads, and not yet added big folder for sharing during which hashing app crashed) and UI is nearly not responding (i mean for numerous minutes no reaction/update), CPU usage is there but quite low, disk activity displayed by htop in like 10MB/s (variable) - again, this is SSD, there should not be HW bottleneck.
On Library tab, i do not see Hashing message yet.

**Comment by slrslr** [comment]
updated from latest git (git remote add origin "https://github.com/zlatinb/muwire.git" 2>/dev/null;git pull origin master) and build (gradlew clean...), changed cores to 2 in conf. file, memory from 256 to 1024 in file. Launch, Seen memory usage 880MB in Status box in MW. CPU usage is quite low and Shared files count increasing without problem on Library tab, only issue was that on Library tab, when i doubleclicked my shared root folder (one that has several hundred thousand files and to which are added newly hashed files now or momentarily) then app frozen and again start being hard to respond, maybe delay of 2 minutes before it update display (CPU, disk activity continue). This unpleasant thing continue for 10 minutes already. Note that i have not reset (empty my share) before this build run. I just let it continue from the "crashed" state.

**Comment by slrslr** [comment]
Update: app got killed again: java.lang.OutOfMemoryError: Java heap space

**Comment by zlatinb** [comment]
Unfortunately there isn't much I can do about the freezing for short periods of time.  Every time MuWire loads a shared file or hashes a new file to be shared it updates the UI.  If there are already many shared files, each update takes longer and longer.

So, if you have several hundred thousand files, while the files initially load from disk or hash the UI will be slow to respond.  After all hashing finishes the UI should become responsive again, but some operations may cause it to freeze for a little while - for example if you sort the Library table by any column that would freeze the UI for a good minute or so.

Regarding the memory, every time the app gets killed because of `OutOfMemoryError` it generates a "heap dump" file.  I can analyze that file if you make it available to me, but it contains sensitive information like your MuWire identity private key and what files you're sharing.  In case you don't care about that, I'll tell you how to let me have the `hprof` file for analysis.

**Comment by slrslr** [comment]
Hi, i have more feedback

CPU limit feature:
- Change of CPU threads limit during runtime works to change CPU utilization. (and "Hashing X files" is correct)
- In my case i think that the default value should be less than half of available threads. Like 1/4.
- Tried to set CPU threads limit to empty value and save, nothing happen, no error, then when i set to -1, i have noticed that the file counter on Library stopped, when i set it to positive value, then it resumed, so this may be tricky and you may either warn user and prevent saving and or when is set an empty / 0 / -1 value, do not limit CPU usage at all (instead of pausing hashing?)
- Setting limit to 99 and then to 2 possibly no problem

Freezing for long time when adding big folder:
As i said, i restored backup of my .MuWire (i call it profile) and i started app with 1024M instead of 256M and set 2 threads CPU limit. Loading of files on Library tab appeared as complete, no hashing so i added mentioned large folder for sharing. quite quickly UI frozen and was like that for 40 minutes, full CPU utilization (despite 2 threads set), so far no auto killing, but the HDD activity was very low so i stopped the app. Renamed my profile folder .MuWire and launched again to create new profile, set 4 threads CPU, memory is at 1024M. and added first shared folder - the larger one with 300K files and 300GB. after some time and small freezes, it was done, but when i have tried to add new folder to share, nothing happened, no raised CPU activity of the processes. So i click exit and start again.
While not all previous files was "loaded" on library tab (still counting), i added another folder, OK, started hashing and finished hashing OK. Btw. i have seen new maximum value of memory usage 969MB out of 996MB displayed in UI, as time went it was moving up and now varying around 930MB soon to reach maximum... and when i have now added another folder for sharing, the UI stopped responding for , low disk activity, CPU remains at hashing level. I do not believe it will start responding.

Idea to improve UI:
If hashing or loading new files can cause UI freeze for minutes, maybe UI should at all times show easy to see message about ongoing process and that it may stop responding during the process, so user do not terminate the app.

Crash log from previous .MuWire profile:
Regarding 1.6GB hprof file, i prefer to let it be, not to share it, but if you think that you will likely find the issue and you will likely be able to fix, then i will take time to prepare it and upload it, send via e-mail (unable to find) [in private](https://bin.disroot.org/).

**Comment by zlatinb** [comment]
Hi, lots of things to respond to, but let me start with the most important:

I. Crash log - `hprof` file.  It will help me a lot if I have access to this file for analysis.  You can encrypt it so that only I can read it like this:
```
# 1. Install GPG - must be available on Manjaro/Arch
# 2. Import my GPG key:
curl https://keybase.io/zlatinb/pgp_keys.asc | gpg --import
# 3. Encrypt the hprof file:
gpg --encrypt -r zlatinb@gmail.com  < name.hprof > name.hprof.gpg
# This will ask you if you are sure you want to use my GPG key.  Say Yes.  It will also take some time.
# 4. Make the .gpg file available for download somewhere.  Only I can decrypt it so it's useless for anyone else.
```
II. Memory
Looks like 1GB is not enough.  I may be able to fix that after analyzing the `hprof` file, but until then you can increase the memory MuWire will use to some value you're comfortable with - 2,3, even 4GB.

III. Warnings in UI:
Unfortunately I can't display a warning while the UI is busy sorting a table for example.  The architecture of the Swing toolkit doesn't allow me to do so.  That is why I recommend the Web Interface to people who share many files.  

IV Input sanitization
I've been really bad at making sure users cannot enter invalid values.  But maybe ability to pause hashing is a good thing.  Either way, I need to fix it, thanks for bringing it up.

And lastly, thank you very much for the time and effort you're putting into this!

**Comment by zlatinb** [comment]
Ok, I analyzed the file.  Unfortunately MuWire simply ran out of memory, there's not much that I can do, at least not without major redesign and rewrite.

So I suggest you increase the available memory to 2GB or 4GB while hashing and observe how much of it gets used.  After the hashing finishes the memory should stabilize.

**Comment by zlatinb** [comment]
Hey @slrslr I have made some very experimental changes to the search index that should reduce memory usage by a lot.  If you want to give them a try, checkout branch `blockfile-index`:
```
git clone https://github.com/zlatinb/muwire
cd muwire
git checkout blockfile-index
./gradlew clean assemble
# ... the rest is the same as before
```

Thanks!

**Comment by zlatinb** [comment]
Update: the changes on the branch are looking good.  I was able to hash 195,000 files with 1GB RAM without any problems.

Looking good for merging soon!

**Comment by slrslr** [comment]
I would like to try it, but i will be unable for a few days unfortunately, i will check it once i am available. 1GB RAM is way above default 256, which is if i am correct a hard limit that user can not easily change or know about. If the app design does not allow dynamic changing of the limit or notifying user upon reaching and allowing user to change limit within interface, maybe interface can show an instruction how to change it manually - along with the notice that the limit is about to be reached. Maybe this 256M limit is not a problem. you know better, i am just concerned this limit does not put away many people who want to share good collection of files.

**Comment by zlatinb** [comment]
I agree with you about the memory limit.  There is no way to change it dynamically though.  The only thing I can do is display a warning if the user tries to share too many files and is with default limit, then point them to documentation how to increase the limit.

**Comment by slrslr** [comment]
> display a warning if the user tries to share too many files and is with default limit, then point them to documentation how to increase the limit.

yes, or display instructions right in the SW.

I was able hash and share 350K files with 1.5GB of memory, average usage was like 1.1GB. So my limit is 1.5GB (way above default 256M). If you will need me to try something specific, let me know. I am on Linux.

**Comment by zlatinb** [comment]
> I was able hash and share 350K files with 1.5GB of memory, average usage was like 1.1GB. 

I assume that is with the latest from git?  I was able to do 195k with 1GB, so the numbers are close enough.

If you want to put in more time in optimizing MuWire's memory usage, there is an interesting tool called `visualvm` which comes with the JDK.  It basically allows you to see in real-time how much memory is being used by what as well as many other metrics of the application.  It should be available on Manjaro/Arch, just type "visualvm" in a terminal, then attach to the `Launcher` application (that's what MuWire will be seen as). Then you can play around with the different screens of VisualVM, you can learn a lot about the internal workings of a JVM and of MuWire this way :)

If you're not that interested in going deeper, that's fine, you've already helped me a great deal in optimizing MuWire and I thank you for it!  Feel free to close this ticket if that's the case.

**Comment by slrslr** [comment]
> If you want to put in more time in optimizing MuWire's memory usage, there is an interesting tool called visualvm

I do not understand these technical things and unsure how i could help you with this tool, possibly better if you use it on your end as you are skilled in this. Thanks for the optimizations you did based on this ticket.
