### ISSUE TITLE
Black icon on black taskbar on Linux

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#60]
Hello,
on Linux, when the taskbar is black/dark grey, the MuWire task icon is hard to find:
![](https://imgur.com/jyzVGaw.png)
(there are two icons on the image, one is qbittorrent, other muwire)
The tray area of the taskbar shows the muwire on white square background so it is not problem.

I was unable to find any image in repository, maybe i would be able to add a white background or such, i have Gimp editor and did some basic editing already.

**Comment by zlatinb** [comment]
Hi, the images are in `gui/griffon-app/resources`.  I the systray icon is the `MuWire-16x16.png` so if you change that file and rebuild MuWire you'll be able to see your changes right away.

**Comment by slrslr** [comment]
Yes, it worked and changed the taskbar icon. Here is how the modified 16x16 icon looks like:
![](https://i.imgur.com/4D0ENn9.png)
File download: https://ufile.io/qge4w28p
i can not add file to https://github.com/zlatinb/muwire/tree/master/gui/griffon-app/resources , no push access..

**Comment by zlatinb** [comment]
Thank you very much, looks good!  I've committed the updated file.
