### ISSUE TITLE
Library filtering/multi word search is exact match, not combination no matter in which order words are or if something is between them

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#61]
Hello,

on Library tab is filtering field. When i have files:

funny cat videos.mp4
funny_cat_videos.mp4
funny.cat.videos.mp4
funny-cat-videos.mp4

and input filter:
funny cat
cat funny

it would be handy to find all the mentioned files. I think that many file names separate words by . _ - and so these files will not appear during casual search request "funny cat". The same way it should work for regular search on "Searches" tab.

Thank You

**Comment by zlatinb** [comment]
Hi, try the latest commit, should work as you describe.

**Comment by slrslr** [comment]
Thank you, filtering and search works well, i think important improvement 👍
