### ISSUE TITLE
Collection Review window folder tree display error

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#74]
This issue occurs only in certain circumstances. To the best of my repro abilities, I think it happens when your Library has several independent folders shared - that is, they aren't all inside one big root folder. The number of files might have something to do with it. The folder structure has to be somewhat elaborate.

Presumably sharing a few folders that contain some combination of files and folders might trigger it. I don't know if the number of folder tree nodes has anything to do with it.

Select the folders from the Library(all of them, they don't need to be expanded in this tree view. Then select Create Collection. Provide a name then go click Review. Wait until the window appears.

Once the tree finishes populating, the top-most folder - which is the collection name folder that includes everything you will share - will be overlapped by the first folder in the collection. Attempting to click on the folder itself in the leftmost top position will show the folder as normal but the first folder in the list will be missing. Attempting to click elsewhere shows the tree node expansion icon over the folder icon. Expanding or collapsing folders results in some manner of misalignment as you cannot fully browse to the bottom of the list. In effect the list cannot be browsed correctly because something is offset somewhere and doesn't match what's showing.

**Comment by zlatinb** [comment]
From the description of the error I think there must be an exception thrown somewhere in the UI thread.  Can you try with logging enabled (at any level is fine) and watch for any exceptions logged?

**Comment by Searinox** [comment]
I really can't find anything. The closest thing I have is:

WARNING org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager$MethodInjectionPoint apply Property 'host' in model (com.muwire.gui.BrowseModel) must be annotated with @griffon.inject.MVCMember.  
WARNING org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager$MethodInjectionPoint apply Property 'core' in controller (com.muwire.gui.BrowseController) must be annotated with @griffon.inject.MVCMember.  

And nothing else mentioning anything related to UI. No exceptions with callstack.

I have strictly connection-related exceptions in the style:
java.lang.Exception: cause
	at net.i2p.client.streaming.impl.Connection.disconnect(Connection.java:785)
...

**Comment by Searinox** [comment]
This is fixed. It might have been the UI global thread management. I can no longer reproduce it.
