### ISSUE TITLE
Using "Show In Library" will reopen the folder after each new piece is downloaded

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#76]
If a user is currently downloading from your MuWire instance, you can right-click the download and select "Show in Library" in order to expand the Library tree and focus the file that is currently being downloaded. Regardless of if you then decide to collapse the folder back, select to browse another folder, or tab away, once the user finishes the current piece of download and starts downloading a new piece, the Library folder is expanded again and the file is re-focused.

**Comment by zlatinb** [comment]
Reproduced it, I think I know why it's happening:

The Library tab gets refreshed fully every time someone tries to download a piece from your MuWire node.  The tree is configured to expand the paths which are selected.  So as long as any file is selected, the tree will expand every time a new piece is requested.

I need to think about how to fix this, there may be an opportunity for an optimization here.

**Comment by zlatinb** [comment]
Fixed in the commit above.  Please verify https://muwire.com/downloads/MuWire-0.8.9-GitHub76.zip and if it works close the issue.

**Comment by Searinox** [comment]
New repro found: by Browsing your own ID(possibly others doing it too, haven't tested) the Library is again expanded.

**Comment by Searinox** [comment]
Seems all good now.
