### ISSUE TITLE
GPG-sign stuff and provide fingerprint in the README & website

### ISSUE THREAD

**Issue by zetok** [zlatinb/muwire#8]
Things that absolutely should be signed and provided with a detached signature:

- release binaries
- release tags
- release tarballs (can be ~automated)

[Making and verifying signatures](https://www.gnupg.org/gph/en/manual/x135.html). If you need more resources on configuration/etc please comment here and I'll post what I have bookmarked on that topic.

Bonus points for signing all commits (including merge commits). Git can be configured to gpg-sign commits & merges.

**Comment by zlatinb** [comment]
Thanks.  I've added my gpg fingerprint and link to the full key in the README.md and created a tag "test-signed-tag".  Will make sure at least tags are signed going forward.
I'll add the same details to the website and provide detached signatures to the binaries as well soon.

**Comment by zlatinb** [comment]
Starting with release 0.4.8 the tag has been signed, also detached signatures have been provided on https://muwire.com .  Key fingerprint and link are available there too.
