### ISSUE TITLE
[Suggestion] Minor Improvements to Options

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#83]
Figured I'd report this in the spirit of minor improvements/finishing touches before a public release.

The following boxes are too narrow in the UI to accomodate common values. This is true as is and even more pronounced if using a bolded font:

MuWire tab:
-Upload slots per user

GUI tab:
-Font name
-Font size number
-Smooth download speeds over(seconds)

Bandwidth tab:
-Inbound Bandwidth (KB)
-Outbound Bandwidth (KB)

Feed tab:
-Feed refresh frequency in minutes

Trust tab:
-Update contact lists every(hours)

Communications tab:
-Maximum chat connections
-Maximum lines of scrollback
-Default chat room
-Send messages in outbox this often(seconds)

Some of these can do with an increase in width of only 25% but the especially small ones should be outright doubled in width to accomodate even small reasonable values.

In addition, at least as far as numeric fields are concerned, I believe a Spinbox type UI element with min and max value constraints would do best because the current textboxes that are being used allow any manner of input, including letters.

**Comment by zlatinb** [comment]
I went throgh the options window and made all text fields 5 columns.  I think it looks ok.

https://muwire.com/downloads/MuWire-0.8.9-GitHub83.zip

**Comment by zlatinb** [comment]
Ok, two more things I may be able to do before the release to make options better

1. Align the text in the text fields to the right instead of to the left
2. Get the list of available fonts and change from text field to a combo box or a spinner

I'll also double the size of the default chat room name.

**Comment by zlatinb** [comment]
Great!  Thanks for the suggestion, closing issue now.
