### ISSUE TITLE
Context menu issue with Uploads

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#86]
From my understanding Upload entries in the Library exist only per piece. As such when a piece is finished uploading, the entry is destroyed and then immediately a new one is created as the downloading instance requests a new piece. This can happen very fast when speeds are good and the piece upload entries quickly pop in and out of existence.

My problem is that if a context menu is open via right-click to a piece and that piece is done and then disappears, all the options in the context menu become useless. You cannot "Show in Library", "Browse Files/Collections", "Subscribe", "Chat", "Message", "Copy full ID". None of them work.

Would it be possible that when the right-click event creates the menu that it instead passes the file path and user ID as values to the context menu instead of relying on the reference to the upload entry? That way the menu options remain functional even if the piece/file finishes uploading and disappears.

**Comment by zlatinb** [comment]
I can't reproduce this unless "Clear finished uploads" in the UI options is checked.  I did the following:

1. started an upload to another instance
2. right-clicked on the upload row, the menu showed up
3. waited until a few pieces got uploaded
4. clicked on "show in library" and it worked.

The same thing doesn't work if "Clear finished uploads" is checked.

What is happening is that the selected row gets lost.  If in the time between the popup menu gets shown and the user clicks on an option the selection of the table is removed, then the option will not do anything.

I need to think what is the best way to fix this...

**Comment by Searinox** [comment]
I do indeed have clear finished uploads checked.

**Comment by Searinox** [comment]
Surprised it wasn't possible to pass immutable args but I don't know how inheritance and hierarchies are enforced in Swing. Even if someone leaves the context menu open for days it shouldn't be a problem. It's only one upload object, it's not a particularly big object in memory, and you can only hold up one single such object at a time so there shouldn't be potential for memory leak.

It's working as far as I tested.
